---

name: Test Find & Install RPM action
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      repo:
        description: 'Repository to install from'
        required: false
        default: 'NSLS2/bitshuffle-rpm'
      tag:
        description: 'Release tag'
        required: false
        default: '0.5.2-2'

jobs:
  test-action:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        rhel_version: [8, 9, 10]
    container:
      image: almalinux:${{ matrix.rhel_version }}

    steps:

      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Make sure curl and jq are installed
        run: |
          dnf -y install curl-minimal jq

      - name: Setup Powertools if RHEL 8
        if: matrix.rhel_version == '8'
        run: |
          dnf -y install 'dnf-command(config-manager)'
          dnf config-manager --set-enabled powertools
      
      - name: Setup CRB if not RHEL 8
        if: matrix.rhel_version != '8'
        run: |
          dnf -y install 'dnf-command(config-manager)'
          dnf config-manager --set-enabled crb

      - name: Install epel repository
        run: |
          dnf -y install epel-release

      - name: Test Find & Install RPM action
        uses: ./
        with:
          rhel_version: ${{ matrix.rhel_version }}
          repository: ${{ inputs.repo || 'NSLS2/bitshuffle-rpm' }}
          release_tag: ${{ inputs.tag || '0.5.2-2' }}
          install_devel: 'true'
